### ISSUE TITLE
URIs for constituents depends on the object

### ISSUE THREAD

**Issue by caknoblock** [american-art/wam#11]
Here is an example URI for an artist: <http://data.thewalters.org/object/id/5995/production/individual/5737> 

It depends on the object, but it should be independent of the object since the same individual could have created multiple objects.  We just need to simplify the URIs for individuals and institutions so that that the object part of the URI is dropped.

**Comment by bsnikhila** [comment]
I believe this has been done because the objects and constituents were in the same file. Only one model is created for the file with the root as Man-Made Object and the constituent URI depending on the object. To remove the dependency, I think the model will have to be split into two, one for objects and one for constituents.

**Comment by caknoblock** [comment]
We will need to build two models, one for objects and one for constituents.  Otherwise, we will end up with a number of duplicate constituents.

**Comment by kateblanch** [comment]
See issue #12  -- tagging @workergnome, there is some URI jumbling happening with Constituents, Geographies and Objects.

**Comment by workergnome** [comment]
Yup—I see the same thing.  We need to use the same URL for the same entity, even across files.  This applies to types as well—all E55_Types need to point to the the same URL across the various objects that refer to it.

(in non-CRM terms:  When a object is classified as a "painting", the URI that we use to mean "painting" should be universal—either an AAT URI or an institution-specific thesaurus URI, but **not** a per-object URI.)

**Comment by bsnikhila** [comment]
Fixed it. Separated the Objects and Constituents into multiple models.

**Comment by kateblanch** [comment]
Hi Nikhila, I can't thank you enough for your awesome work addressing our issues!
The Object constituent is working better...individuals and institutions display exactly right. When the constituent is a culture however a display name is missing. 

On review site -- http://review.americanartcollaborative.org -- E22 Objects -- Artist field, I enter this URI:
http://data.thewalters.org/object/19600

This object's constituent is "American".  Here's what's being returned:
Actor Name - blank / no name value showing up
Actor Type - 	crm:E39_Actor	
Actor Class - http://data.thewalters.org/constituent/6184

Here is the detail from the review site:

The current query was:

```ttl
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX schema: <http://schema.org/>

SELECT ?actor_name ?actor_type ?actor_class
WHERE {
<http://data.thewalters.org/object/19600> a crm:E22_Man-Made_Object ;
   crm:P108i_was_produced_by ?production_event .

?production_event a crm:E12_Production ;
  crm:P14_carried_out_by ?actor_class .

OPTIONAL {
  ?actor_class a ?actor_type .
}
OPTIONAL {
  ?actor_class rdfs:label ?actor_name.
}

}


```

**Comment by bsnikhila** [comment]
This is fixed. It now shows "American".

**Comment by workergnome** [comment]
Looks good to me
