### ISSUE TITLE
Two production URIs

### ISSUE THREAD

**Issue by workergnome** [american-art/wam#12]
It looks like there are two different production IDs:

for <http://data.americanartcollaborative.org/page/wam/object/id/9895>, there is `<wam:object/id/9895/place_of_origin>` and `<wam:object/id/9895/production>`, but they appear to refer to the same event.  They are probably mapped in two different files, and should be consistently assigned the same URI, unless they're explicitly not the same event (which seems unlikely)?

**Comment by kateblanch** [comment]
There should not be 2 production URIs in this instance. I may have deduced the cause of this problem wrong, and honestly don't know how to fix it...but here's my take.

This URI needs to include the E39 Actor from the Constituents model - wam:object/id/9895/production
This URI is a Geographical reference to where the Production event occured - wam:object/id/9895/place_of_origin

**Comment by bsnikhila** [comment]
It was because the data was in 2 files. I fixed it. We now have only one production URI
