### ISSUE TITLE
Cannot distinguish between various images

### ISSUE THREAD

**Issue by workergnome** [american-art/wam#13]
All images are mapped identically, which means the Browse application cannot distinguish between the various types of images.   The provided data has both a type and a primary/non-primary flag, which should be used to apply appropriate types.

If you wanted to be particularly helpful, you could also add a type for color/bw.

**Comment by bsnikhila** [comment]
I changed the model to only primary images, since there is no model give for non-primary images on the review site.

**Comment by kateblanch** [comment]
I'm ok with the mapping of primary images only. This might make the browse app simpler in it's design (partners vary as to their provision of primary / non-primary - everyone has primary but not everyone has non-primary images).

**Comment by workergnome** [comment]
This is really a call for you and the Data working group—we should figure out how we're handling this across all institutions.  

Adding the AAT type we're using for  primary types would be the other solution.

**Comment by kateblanch** [comment]
Given the time constraints on the project, let's just go with primary only.
