### ISSUE TITLE
Image Credit Line not modeled.

### ISSUE THREAD

**Issue by workergnome** [american-art/wam#14]
The image credit line is provided, but not modeled.

This would be a useful thing to have available when displaying the image.

**Comment by bsnikhila** [comment]
I don't the review site has provided a way to model image credit line. Would you like me to model it the same as Object credit line? Or would you like me to put it as rdfs:label in the model for Image?

**Comment by workergnome** [comment]
Model it the same as the Object credit Line.

**Comment by bsnikhila** [comment]
Alright

**Comment by kateblanch** [comment]
Hi there, I don't see Image Credit Line on the model though I see you updated it a day ago.
Admittedly I am practicing reviewing the models against the data...so might have missed it.
Let me know if this is resolved. Cheers!

**Comment by bsnikhila** [comment]
I had a discussion with Craig about this. The URI we use for the Image is the URL itself. But we cannot use this to create the URI for Credit line. So could you please help me out with this?

**Comment by workergnome** [comment]
@bsnikhila, I'm curious about the 'cannot'.  Is this a Karma limitation?  For instance, both the British museum and YCBA currently models their images in this way, so it's not a limitation of the model, RDF, or CRM.

**Comment by szeke** [comment]
There are two issues with the image url.

1) The URL has characters that need to be url encoded, we can do that.
Nikhila, use a python function to encode URLs before using it as a URI

2) The URI will not be in the same domain as the other URIs, so using it as
a subject creates linked data that does not dereference so that the
properties defined for it cannot be retrieved by a consumer.

The correct solution is to give the Image Object a proper URI and put the
URL as a data property.

We can do it either way.

p

**Comment by kateblanch** [comment]
Hi Pedro and Nikhila - I have no idea how to advise you to proceed. Obviously doing it the correct way is idea, My priority is that is works for the browse app -- @workergnome, any ideas which will work better?

**Comment by workergnome** [comment]
At this point, I care more about consistency between institutions than the specific details of the mapping.  The review tool's model was designed to match the mappings used by SAAM, BM, and YCBA, and I'm not interested I re-opening this discussion again—I'll work around whatever is implemented, as long as it's consistent across all the institutions.

**Comment by kateblanch** [comment]
@workergnome - OK to close? This seems to have been addressed with the IIIF workaround and the default image rights statements?

**Comment by workergnome** [comment]
I think closing "wontfix" is probably the right solution here. We haven't solved the underlying problem, but I don't think it's going to be solved in this revision.

(For those following along, the underlying problem is if an digital image file (http://example.com/image.jpg) and the concept of the image (http://example.com/images/image.rdf) are two distinct things, or can be referred to by the same URI.  It's a long-standing, messy conversation in this world.)
