### ISSUE TITLE
(!) add type, label and ULAN link for each institution

### ISSUE THREAD

**Issue by workergnome** [american-art/wam#15]
There's no indication in the LOD that Walters is the owner of this object.

**Comment by kateblanch** [comment]
Hey @workergnome , I am using Object Under Jurisdiction Of for this. 
<ObjUnderJurisOf>The Walters Art Museum, Baltimore, Maryland, http://thewalters.org</ObjUnderJurisOf>
I'll try and ascertain whether this value get mapped? 
This might come up in lots of partner data sets.

**Comment by workergnome** [comment]
Works for me—here's the model I'm using to look for this property:

http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_16-search_0

**Comment by workergnome** [comment]
@kateblanch: I'm not sure what "Object Under Juristiction Of" refers to—is that a ontology property?

Also—is your preferred URI for the walters-as-constituent your base URL?  Doesn't matter to me, but it might make it harder to dereference that URI and get back linked data in the future.  I've seen people use the ULAN term for their ID, as well, as well as whatever their internal constituent record ID is.

**Comment by kateblanch** [comment]
"Object Under Jurisdiction Of" is the attribute (column) name in our WAM raw data that points to us as an owner. 

As for our preferred URI, we're not in the Getty ULAN but we can use our TMS Constituent ID - 8773. 

Does that help answer this issue?

**Comment by workergnome** [comment]
That's enough for me!

**Comment by kateblanch** [comment]
Let me make sure I am going to do the next right thing here.
Object Under Jurisdiction Of (column name in the data) is mapped to E40_Legal_Body.
The value presently is "The Walters Art Museum, Baltimore, Maryland, http://thewalters.org".

Do I need to update the data so that the value is "8773" or "The Walters Art Museum, Baltimore, Maryland [8773]"? If yes, I do need to update the value of this column...let me know which value you were expecting.

Thanks @workergnome !

**Comment by workergnome** [comment]
Let's see what the ISI student wants in that value—we're in agreement of what it _should_ be, but they'll know what's easiest for them.

**Comment by bsnikhila** [comment]
The current owner has been mapped as follows :
http://data.americanartcollaborative.org/page/wam

Please let me know if this is alright.

**Comment by workergnome** [comment]
@bsnikhila, I can't see anything there.

**Comment by bsnikhila** [comment]
I am sorry, this is the URI : http://data.thewalters.org/
It is redirected to data.americanartcollaborative.org/wam

**Comment by kateblanch** [comment]
The URI for current owner of http://data.thewalters.org/ works great, the mapping works. 
The skos:ExactMatch link to the ULAN entry does not work, though - http://vocab.getty.edu/ulan/500279110, maybe we can address that?

**Comment by workergnome** [comment]
Works for me—  @bsnikhila, was this resolved?

**Comment by bsnikhila** [comment]
@kateblanch What exactly do you mean by the ULAN entry does not work?

**Comment by VladimirAlexiev** [comment]
According to #20 (resolveD), it should be http://data.thewalters.org (no trailing slash).
That URL returns no data (because there are no outgoing triples), but this query returns the objects of WAM: 
```sparql
select * {
  ?x ?p <http://data.thewalters.org>
}
```
Adding ULAN link would be nice but is optional.

**Comment by kateblanch** [comment]
Hi @bsnikhila - when I follow the link to the ULAN entry you provided in your comment above (http://vocab.getty.edu/ulan/500279110) I get the following page error:
HTTP Status 500 - unable to create new native thread

I'm a little confused as to why I get a 404 error at http://data.thewalters.org - I feel like it used to work. Can you direct me on how to help resolve this?

**Comment by workergnome** [comment]
@kateblanch I think the ULAN error is an actual error on ULAN, not something we're doing.  I've gotten it to work about 20% of the time I try it, so it's a correct URL.  ULAN is just having a bad day.

The 404 is a problem, though.

**Comment by VladimirAlexiev** [comment]
>500 - unable to create new native thread

I guess the service monitoring there caught it and restarted the GVP service, now is ok. @workergnome if you see it again, please post at the ggroup https://groups.google.com/forum/#!forum/gettyvocablod..

@kateblanch http://data.thewalters.org returns no data (because there are no outgoing triples). So the 404 is ok.

**Comment by workergnome** [comment]
Well, there should be at least a label for http://data.thewalters.org, and probably the ULAN link of which the rest of this issue concerns.

**Comment by VladimirAlexiev** [comment]
Agree, and that applies to all museums (also type: Legal_Body). Changed the title accordingly.
@kateblanch & @workergnome, I think it's best if you do this by hand?

**Comment by bsnikhila** [comment]
I have added the Ulan link to whichever museum had provided it in the spreadsheet.

**Comment by kateblanch** [comment]
I'm a little sideways on this - @bsnikhila which spreadsheet has the partner ULAN links?
@VladimirAlexiev  - if we add ULAN entries by hand to the spreadsheet will that resolve this issue?

**Comment by VladimirAlexiev** [comment]
@kateblanch If you add it to a sheet and @bsnikhila generates statements out of it, the issue will be resolved

**Comment by kateblanch** [comment]
Ok, thanks @VladimirAlexiev. Need to know if there's an existing spreadsheet or if I should create one - @bsnikhila, can you advise? If i need to create one, what repo should I store it in? Alternately, I could add a ULAN link to the "Object Under Jurisdiction Of" (column name in the source data).

**Comment by kateblanch** [comment]
Do we need a spreadsheet with all 14 partner names and their ULAN ids? I'm sorry to drag this simple issue out, I'm just confused. Thanks for your patience!

**Comment by VladimirAlexiev** [comment]
Yes, we need all partners.

**Comment by workergnome** [comment]
@kateblanch: isn't this included in the partner spreadsheet you sent around a couple months ago?

**Comment by bsnikhila** [comment]
Yes, the spreadsheet that had all details about the partners had ULAN IDs for most museums. WAM, CBM, SAAM, NMWA and AAA don't have ULAN IDs mentioned in that spreadsheet.

**Comment by kateblanch** [comment]
Spreadsheet is updated on Google Docs with partner's ULAN IDs for WAM, SAAM, AAA and DMA. 
https://docs.google.com/spreadsheets/d/1WXzkzi8Pk4j3oOvpvHA4nWnE5_vhBuE_sgb14J06CDA/edit#gid=1014481183

CBM and NMWA don't appear to have ULAN entries, so I could not provide an ID. All other partners have one, though! Hope this helps :)

**Comment by VladimirAlexiev** [comment]
Asked Patricia to add to ULAN: https://jira.getty.edu/browse/ITSLOD-513

**Comment by VladimirAlexiev** [comment]
500404081  Crystal Bridges Museum of American Art
500404082  National Museum of Wildlife Art

Cheers!

**Comment by workergnome** [comment]
Great.  Updated the spreadsheet.

**Comment by kateblanch** [comment]
@workergnome  -- OK to close this?

**Comment by workergnome** [comment]
I think @bsnikhila has completed this, so will close.  Will reopen in individual institutions if they're missing ownership information.
