### ISSUE TITLE
Specific mediums appear to have been modeled as "Subject"

### ISSUE THREAD

**Issue by workergnome** [american-art/wam#16]
If I look at, say, http://data.americanartcollaborative.org/page/wam/object/id/4021, the "crm:P62_depicts" are paper and  watercolor, which appear to be mediums, not subjects.  This appears to hold true for all the objects.

**Comment by kateblanch** [comment]
This is a mistake that needs correction. The terms that are provided are labeled with a type. The types are: 
AAT Support/Ground/Base
AAT Materials
AAT Technique
AAT Color
AAT Object Name 
Copying the PhysicalDescription node from this object here, for reference. We actually don't have a Subject term present in this data. @caknoblock  - not sure who's around to help on this.....or could you provide more insight into this? Thanks!

```
 <PhysicalDescription>
      <Medium>watercolor on paper</Medium>
      <PhysicalDescriptionTerms>
        <ThesXRefID>730385</ThesXRefID>
        <ThesXrefType>AAT Support/Ground/Base</ThesXrefType>
        <Term>paper (fiber product)</Term>
        <SourceTermID>300014109</SourceTermID>
        <PhysDescAuthority>Getty AAT, http://www.getty.edu/research/tools/vocabularies/aat/index.html</PhysDescAuthority>
      </PhysicalDescriptionTerms>
      <PhysicalDescriptionTerms>
        <ThesXRefID>856184</ThesXRefID>
        <ThesXrefType>AAT Materials</ThesXrefType>
        <Term>watercolor</Term>
        <SourceTermID>300015045</SourceTermID>
        <PhysDescAuthority>Getty AAT, http://www.getty.edu/research/tools/vocabularies/aat/index.html</PhysDescAuthority>
      </PhysicalDescriptionTerms>
    </PhysicalDescription>
```

**Comment by bsnikhila** [comment]
Fixed it, changed it to Medium
