### ISSUE TITLE
Clarification regards AAC_Constituents

### ISSUE THREAD

**Issue by raviraju** [american-art/wam#2]
1) Difference bw ConGeographyText and ThesGeographyTerm, It is observed that ConGeo gives more details compared to ThesGeo?
<ConGeographyText> France, Paris</ConGeographyText>
<ThesGeographyTerm>Paris</ThesGeographyTerm>

2)   Why do we have multiple occurences of Birth and Death info, which of them to be considered for mapping ?
   79:     <ObjectID>333</ObjectID>
   83:         <ConstituentID>7142</ConstituentID>
   86:         <DisplayName>Samuel Colman</DisplayName>
   94:         <ConGeographyID>3785</ConGeographyID>
   95:         <ConGeoCode>Death Location</ConGeoCode>
   96:         <ConGeographyText> USA, New York, New York</ConGeographyText>
   98:         <ThesGeoType>Birth Location</ThesGeoType>
   99:         <ThesGeographyTerm>Portland</ThesGeographyTerm>
  110:         <ConGeographyID>3785</ConGeographyID>
  111:         <ConGeoCode>Death Location</ConGeoCode>
  112:         <ConGeographyText> USA, New York, New York</ConGeographyText>
  114:         <ThesGeoType>Death Location</ThesGeoType>
  115:         <ThesGeographyTerm>New York</ThesGeographyTerm>
  126:         <ConGeographyID>3786</ConGeographyID>
  127:         <ConGeoCode>Birth Location</ConGeoCode>
  128:         <ConGeographyText> Maine, Portland</ConGeographyText>
  130:         <ThesGeoType>Birth Location</ThesGeoType>
  131:         <ThesGeographyTerm>Portland</ThesGeographyTerm>
  142:         <ConGeographyID>3786</ConGeographyID>
  143:         <ConGeoCode>Birth Location</ConGeoCode>
  144:         <ConGeographyText> Maine, Portland</ConGeographyText>
  146:         <ThesGeoType>Death Location</ThesGeoType>
  147:         <ThesGeographyTerm>New York</ThesGeographyTerm>

**Comment by workergnome** [comment]
Looking over this, for issue #2 (and, would you mind in the future keeping one topic per issue?) it looks like there's a level of grouping that's missing for the data here? @kateblanch, any input on this?

**Comment by kateblanch** [comment]
Regarding #1. 
ConGeographyText is a text "label" for the geography, in some cases it will be more descriptive than  ThesGeographyTerm. ThesGeographyTerm will always map to the TGN. 

Regarding #2.
Thanks, @workergnome - there is some strange (erroneous) duplication going on here. I can fix the duplication and resubmit the data file, but let me clarify - are you referring to:
<ConGeoCode> duplicates  <ThesGeoType> and 
<ConGeographyText> duplicates or is very similar to <ThesGeographyTerm>?

Just like in #1 above, the fields with prefix "Con" is going to be a label and the fields with prefix "Thes" will have Getty TGN IDs. I wonder if I forgot the TGN ID's for the data points in #2.

**Comment by workergnome** [comment]
Referring to exact duplicates.  Also, not sure if it's a problem for Karma that the explicit order of tags matters, not just the XML structure.  (for instance, if I selected  `<ConGeographyID>` for this, I'd get four elements—but they're referring to two different things. (birth and death) and the only way to know which one it is it to look for the tag preceding it.  Again, not sure if it's a problem, but it would confuse _my_ parser...

**Comment by caknoblock** [comment]
I think this will be a problem for Karma too.   I don’t think this is valid XML since XML data is considered unordered.

**Comment by kateblanch** [comment]
I will fix the duplication issues and re-upload this data file to the set. It's needless to have this extra data, it definitely confuses things (me included). 
@raviraju - does that work for you? You'll have to pause on modeling this data file.
I can get this complete in the next day or so.

**Comment by raviraju** [comment]
@kateblanch  : Sure Kate, it would also be great if we have an access to a brief description of various fields for different data sources. I found some info for Collections, Objects, Geographies, Exhibitions, Museum Locations at https://github.com/WaltersArtMuseum/walters-api, such brief notes about the fields will help anyone in future to have clear understanding of sources and their mappings.

**Comment by kateblanch** [comment]
@caknoblock and @workergnome -- I've fixed the Constituent Geo data so that one unique ID will present for each geo entry. If you can further help me / tell me what I'd need to do to fix the XML that would be super. Here is a new sample:

```
 <ObjectRelatedConstituent>
        <ConstituentID>4652</ConstituentID>
        <CreatorDispOrder>1</CreatorDispOrder>
        <Role>Artist</Role>
        <DisplayName>Eastman Johnson</DisplayName>
        <CreatorULANID>500008685</CreatorULANID>
        <Gender>male</Gender>
        <ConAuthority>Getty ULAN, http://www.getty.edu/research/tools/vocabularies/ulan/index.html</ConAuthority>
      </ObjectRelatedConstituent>
    </Constituents>
    <ConstituentGeography>
      <ObjectRelatedConstituentGeography>
        <ConThesGeographyID>630597</ConThesGeographyID>
        <ThesGeoType>Birth Location</ThesGeoType>
        <ThesGeographyTerm>Lovell</ThesGeographyTerm>
        <ConGeoLatitude>44 07</ConGeoLatitude>
        <ConGeoLatDirection>N</ConGeoLatDirection>
        <ConGeoLongitude>070 53</ConGeoLongitude>
        <ConGeoLongDirection>W</ConGeoLongDirection>
        <ConGeoLatitudeNumber>44.1160</ConGeoLatitudeNumber>
        <ConGeoLongitudeNumber>-70.8830</ConGeoLongitudeNumber>
        <ConGeoTGNSourceTermID>2045102</ConGeoTGNSourceTermID>
        <ConGeoAuthority>Getty TGN, http://www.getty.edu/research/tools/vocabularies/tgn/</ConGeoAuthority>
      </ObjectRelatedConstituentGeography>
      <ObjectRelatedConstituentGeography>
        <ConThesGeographyID>815394</ConThesGeographyID>
        <ThesGeoType>Death Location</ThesGeoType>
        <ThesGeographyTerm>New York</ThesGeographyTerm>
        <ConGeoLatitude>40 42</ConGeoLatitude>
        <ConGeoLatDirection>N</ConGeoLatDirection>
        <ConGeoLongitude>074 00</ConGeoLongitude>
        <ConGeoLongDirection>W</ConGeoLongDirection>
        <ConGeoLatitudeNumber>40.7000</ConGeoLatitudeNumber>
        <ConGeoLongitudeNumber>-74.0000</ConGeoLongitudeNumber>
        <ConGeoTGNSourceTermID>7007567</ConGeoTGNSourceTermID>
        <ConGeoAuthority>Getty TGN, http://www.getty.edu/research/tools/vocabularies/tgn/</ConGeoAuthority>
```

@raviraju  -- I've just uploaded a V2 data file for the Constituents. I think I've addressed the confusing duplication. See my note to Craig and David above though, any advice from any of you is so appreciated - I'm new to publishing data in XML.

It will take me a little longer to compile a data dictionary that defines what the fields are within our data, but I will work on it. In the meantime, please don't hesitate to ask me about specific definitions of any you come across.

**Comment by workergnome** [comment]
That looks much cleaner, @kateblanch.  Thank you!
