### ISSUE TITLE
(!) Owner URLs missing; should be global

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/wam#20]
this query on [yasgiu.org](http://yasgui.org/short/BycX0aTKe) returns a bunch of different URLs for who owns the WAM objects, eg http://data.thewalters.org/object/28499/current_owner. But all of them have the same label "The Walters Art Museum, Baltimore, Maryland, http://thewalters.org"

That's crazy. Use one URL: http://thewalters.org. And say it has `foaf:homepage <http://thewalters.org>`

**Comment by VladimirAlexiev** [comment]
Autry is much better, it uses one URL http://data.americanartcollaborative.org/autry/object/owner/autrymuseumoftheamericanwest.
But that's a very roundabout way of saying Autry! Just use https://theautry.org/. The sky won't fall if you then say:
```ttl
<https://theautry.org> foaf:homepage <https://theautry.org>
```

**Comment by VladimirAlexiev** [comment]
Owner URLs are very important because I imagine @workergnome needs them to show paintings per-collection. So I'll check them all

**Comment by VladimirAlexiev** [comment]
Uh oh, only 2 museums are listed as owners of their works:
```sparql
select ?l (count(*) as ?c) {
  ?x crm:P52_has_current_owner ?y.
  ?y rdfs:label ?l
} group by ?l
```
Autry Museum of the American West : 193
The Walters Art Museum, Baltimore, Maryland, http://thewalters.org : 800

This is out of 142k works:
```sparql
select  (count(*) as ?c) {?x a crm:E22_Man-Made_Object} 
```
@caknoblock how to raise the importance of this issue?

**Comment by workergnome** [comment]
I've got no problem with whichever URI they choose—the only reason I could see to use a URI other than the root domain is if we wanted to ensure that that URI could be dereferencable into RDF, which would be useful, and I wasn't sure if that would be possible with root domains.

**Comment by kateblanch** [comment]
I like the simplicity of using Use one URL: http://thewalters.org but I will heed to whatever recommendation @VladimirAlexiev  and  @workergnome resolve to. If, out of this issue, we could come up with a consistent Owner URL pattern for all the partner museums I think that would be helpful. Individually, partners are not lilkely to know how to choose one that works.

**Comment by VladimirAlexiev** [comment]
@workergnome If semantic dereferencability is required, then the best is to use these (see https://github.com/american-art/semantic-hosting/issues/4 for the issue of Branding):
- http://data.theautry.org
- http://data.thewalters.org

These will redirect to:
- http://data.americanartcollaborative.org/autry
- http://data.americanartcollaborative.org/wma

What's important is that ALL objects must have `crm:P52_has_current_owner`, and those must be consistent, because you need to hard-code them in the app

**Comment by workergnome** [comment]
I think that the root of the data domain is a fine pattern.

**Comment by bsnikhila** [comment]
The current owner has been added to all museums now.
As and when I work on the other museums' issues, I will check if their Department field has the current owner associated with it.

**Comment by VladimirAlexiev** [comment]
Thanks @bsnikhila! The yasgui query returns these values:

- great
http://data.crystalbridges.org
http://data.theautry.org
- remove trailing slash?
http://data.thewalters.org/
- IMHO should be as above
http://data.americanartcollaborative.org/GM
http://data.americanartcollaborative.org/acm
http://data.americanartcollaborative.org/ccma
http://data.americanartcollaborative.org/dma
http://data.americanartcollaborative.org/ima
http://data.americanartcollaborative.org/npg
http://data.americanartcollaborative.org/puam
http://data.americanartcollaborative.org/saam
- really must fix this
http://data.americanartcollaborative.org/nmwa/data.americanartcollaborative.org/nmwa

**Comment by workergnome** [comment]
Oh, man.  NMWA needs to be fixed.  Agree with Walters, just for consistency sake.

@VladimirAlexiev, I believe that most of of the other ones will be adjusted once the institutions have set up their redirects, but I don't believe any of those have yet.

**Comment by bsnikhila** [comment]
NMWA is fixed.
http://data.americanartcollaborative.org/nmwa

**Comment by VladimirAlexiev** [comment]
@bsnikhila please remove trailing slash from http://data.thewalters.org/ and close it

**Comment by bsnikhila** [comment]
Done.
