### ISSUE TITLE
medium_text is mapped using two predicates

### ISSUE THREAD

**Issue by workergnome** [american-art/wam#21]
on http://data.americanartcollaborative.org/page/wam/object/155:

http://data.americanartcollaborative.org/page/wam/object/155/medium_text is mapped using both crm:P129i_is_subject_of and crm:P67i_is_referred_to_by.  

The mapping specifies only crm:P67i_is_referred_to_by.  Please remove the other mapping.

Thanks!

**Comment by bsnikhila** [comment]
Fixed.

**Comment by workergnome** [comment]
Confirmed.
