### ISSUE TITLE
Missing creator when not a person

### ISSUE THREAD

**Issue by workergnome** [american-art/wam#22]
http://data.americanartcollaborative.org/page/wam/object/35485 was created by Tiffany's, which is a constituent, but is not linked.

**Comment by bsnikhila** [comment]
These seem to be all the role values in the data file.
Which ones should be modeled as Artist?

painter
artist
designer
goldsmith
sculptor
jeweler
manufacturer
patron
engraver(printmaker)
founder
engraver(inciser)
author
distributor
binder
publisher

I have only considered Painter, Artist, Sculptor, Designer and Goldsmith as Artists. I will include Manufacturer. Should I include all the others too?

**Comment by workergnome** [comment]
This is really a question for @kateblanch, but I think they're all forms of creators, with the _possible_ exception of patron?

**Comment by kateblanch** [comment]
Hi @bsnikhila! 
@workergnome is right-o on this -- all the roles should be mapped as Artist with the exception of Patron.
Please make sure this is reflected in all the constituent files (because I know you have split constituents into Individual, Institution and Culture.

**Comment by willhays** [comment]
Hi @workergnome and @bsnikhila,

With Kate no longer at WAM (I'm still in mourning), I'm taking over as the Walters rep for AAC. Is there anything I need to do to help resolve this issue?

**Comment by bsnikhila** [comment]
Should patrons continue to be constituents but not mapped as creators, or should they not be mapped as constituents at all?

**Comment by willhays** [comment]
It would be great if they could be included, just not mapped as creators.

**Comment by kateblanch** [comment]
Hi @bsnikhila - this looks like it's still unresolved. Please add these roles to the modeling for Creator/Artist:

painter
artist
designer
goldsmith
sculptor
jeweler
manufacturer
patron
engraver(printmaker)
founder
engraver(inciser)
author
distributor
binder
publisher

**Comment by bsnikhila** [comment]
Done.
