### ISSUE TITLE
Titles are not per-object

### ISSUE THREAD

**Issue by workergnome** [american-art/wam#23]
It looks like all titles are mapped to a thesaurus, which causes problems when multiple objects have the same title.  See http://data.americanartcollaborative.org/page/wam/thesauri/title/georgewashington

for an example.

Titles should be per-object.

**Comment by bsnikhila** [comment]
I have used the Title ID for the Title URIs. Hopefully this should work fine.
http://data.americanartcollaborative.org/page/wam/object/155

**Comment by workergnome** [comment]
Looks great.  Thank you.
