### ISSUE TITLE
Title type URLs should be global not per-object

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/wam#24]
http://data.thewalters.org/object/523/title/76307/title_type is "Alternate".
Using such URLs is wasteful, and doesn't allow you to easily find all titles of a given type.
Use http://data.thewalters.org/thesaurus/title_type/alternate.

**Comment by bsnikhila** [comment]
Fixed.
http://data.thewalters.org/thesauri/title_type/alternate
