### ISSUE TITLE
Is medium/classification issue a data or mapping issue?

### ISSUE THREAD

**Issue by workergnome** [american-art/wam#25]
For http://data.americanartcollaborative.org/page/wam/object/10053, when I look at `crm:P45_consists_of`, there's "Graphite", "Paper", and "Drawings".  @kateblanch, is this messy data, or have we mapped classification and materials to the same category by mistake?

**Comment by kateblanch** [comment]
This looks fixed to us...so it was likely mapping classification and materials to the same category?
@workergnome - take a peak and perhaps we can close.

**Comment by workergnome** [comment]
Looks fixed to me.
