### ISSUE TITLE
WAM material: AAT should be URL not literal

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/wam#26]
http://data.americanartcollaborative.org/page/wam/material/paperfiberproduct has skos:broadMatch	
http://vocab.getty.edu/aat/300014109. But that last thing is a literal, should be URL.

There are 91 problems like this, all are in WAM:
```sparql
select * {
  ?x skos:broadMatch ?y
  filter (!isURI(?y))
}
```

@kateblanch Could the WAM person please check where eg these came from
- http://data.americanartcollaborative.org/page/wam/material/illustrations
- http://data.americanartcollaborative.org/page/wam/material/tumblersdrinkingglasses

A work can hardly be made of illustrations or drinking glasses, so maybe these values should be in "object type" not in "material".
(I did see once a record for a modern art installation made of 2000 lightbulbs, but the above is not such case).

**Comment by workergnome** [comment]
For the first part, @bsnikhila, can you verify that AAT terms are URLs, not strings?

For the second part, #25 is about the same thing: @kateblanch, can you clarify if this is a data problem or a mapping problem?

**Comment by kateblanch** [comment]
A couple things going on here, so I will try and provide useful details.
1) I don't quite understand the AAT URL vs. String problem so I can't contribute to resolving that. It would be great though, to understand why text literals are part of the URL instead of IDs. E.g. why does this url feature "tumblersdrinkingglasses" instead of a ULAN ID "300043257"? The text strings in the URLs seem problematic for many reasons, but perhaps I'm off base on that. I'm open to learning why a text string in a URL would be better than an ID. 

2) We provided two types of "physical description terms" - AAT Materials and AAT Object Name.
The term "tumblers (drinking glasses)" is used on 2 objects, and given the right type in the source data as "AAT Object Name". @bsnikhila - were both types, AAT Materials and AAT Object Name mapped accordingly? It looks like they were combined into e57_Material. 
Here is how the source data appears for object 33060:

```
  </ObjRecord>
  <ObjRecord>
    <ObjUnderJurisOf>The Walters Art Museum, Baltimore, Maryland, http://thewalters.org</ObjUnderJurisOf>
    <ObjectID>33060</ObjectID>
    <DataDateStamp>2016-04-26T13:10:25.753</DataDateStamp>
    <ObjectNumber>47.368</ObjectNumber>
    <ResourceURL>http://art.thewalters.org/detail/33060</ResourceURL>
    <Classification>Objects: Minerals &amp; Inorganics</Classification>
    <SubClassification>Cut &amp; Other Glasswares</SubClassification>
    <CurrentLocation>Centre Street: Fourth Floor: Lobby</CurrentLocation>
    <Provenance>Purchased by William T. Walters, Baltimore; inherited by Henry Walters 1894; by bequest to Walters Art Museum, 1931.</Provenance>
    <CreditLine>Acquired by William T. Walters</CreditLine>
    <PublicDescription>One of a group of six glasses, each of a different style, selected from a set formerly used by William T. Walters.</PublicDescription>
    <Inscription>[Monogram] WTW</Inscription>
    <Dated>after 1861</Dated>
    <DateBegin>1861</DateBegin>
    <DateEnd>1890</DateEnd>
    **<PhysicalDescription>
      <Medium>glass</Medium>
      <PhysicalDescriptionTerms>
        <ThesXRefID>776188</ThesXRefID>
        <ThesXrefType>AAT Materials</ThesXrefType>
        <Term>glass</Term>
        <SourceTermID>300010797</SourceTermID>
        <PhysDescAuthority>Getty AAT, http://www.getty.edu/research/tools/vocabularies/aat/index.html</PhysDescAuthority>
      </PhysicalDescriptionTerms>
      <PhysicalDescriptionTerms>
        <ThesXRefID>819336</ThesXRefID>
        <ThesXrefType>AAT Object Name</ThesXrefType>
        <Term>tumblers (drinking glasses)</Term>
        <SourceTermID>300043257</SourceTermID>
        <PhysDescAuthority>Getty AAT, http://www.getty.edu/research/tools/vocabularies/aat/index.html</PhysDescAuthority>
      </PhysicalDescriptionTerms>
    </PhysicalDescription>**
  </ObjRecord>
```

**Comment by workergnome** [comment]
@kateblanch:

URIS built from unique IDs are always better than URIS built from strings.  Typically, we only want to use strings if there's no way to create a unique id that will persist if the data is changed.  

The strings vs. URL is not something you have to solve, but to explain:  Think about the difference between the `http://www.example.com` and http://www.example.com.  One is just letters, and one is a link.  In linked data, we've got the same sort of thing.  

```ttl
_:object foaf:homepage "http://www.example.com".
_:object foaf:homepage <http://www.example.com>.
```

The first one is just letters and symbols, the second is an explicit link.

**Comment by workergnome** [comment]
I created a new issue for the second point at #27.

**Comment by kateblanch** [comment]
I agree and anticipated that the URIs would contain unique IDs where possible. I'm unsure why so many URIs are being created from text strings where IDs are available, but thanks for absolving me of the need to fix it :) Thank you too for explaining the details! Everything I am learning on this project is much appreciated!

**Comment by bsnikhila** [comment]
Fixed the AAT URL.
