### ISSUE TITLE
URL for a page that lists all objects?

### ISSUE THREAD

**Issue by kateblanch** [american-art/wam#28]
Is there a URL where I can return a list of all the objects?
For example, instead of going to data.thewalters.org/object/9356...can I just go to data.thewalters.org/object and see all the objects listed? 
I know, I know this is a 1st grade question!

**Comment by workergnome** [comment]
There's not a page for it, but this will get you there:

http://yasgui.org/short/rJqNH27Al

**Comment by kateblanch** [comment]
Thank you for teaching me how to SPARQL-query!
I swear I'll get there sometime soon :)
