### ISSUE TITLE
Modelling of TGNTermID in AAC_Geography

### ISSUE THREAD

**Issue by raviraju** [american-art/wam#3]
Do we need to model TGNTermID, if so I would like to seek some guidance on, which CRM-CIDOC Entity does it map to.
Do we need to provide reference to http://vocab.getty.edu/tgn/7012149

**Comment by workergnome** [comment]
Absolutely.  That's essential—it's the link to the external vocabulary, which means that we will not need to reconcile this term.

There is a `E53 Place`, which is a `skos:exactMatch` to http://vocab.getty.edu/tgn/7012149-place (note it's to the Real World Object, not the concept.)

**Comment by kateblanch** [comment]
@workergnome's reply works for me - if you need more info, ping me back otherwise I will not provide more information on this issue.

**Comment by raviraju** [comment]
Thanks David @workergnome 
Kate @kateblanch please confirm if my interpretation here is right.

So to summarize, there are two id's to identify geography : GeographyID(internal identifier by museum) and TGNTermID(external reference identifier)
A Sample Record Modelled : 
{
    "a": ["E22_Man-Made_Object"],
    "P62_depicts": {
        "a": ["E53_Place"],
        "P1_is_identified_by": [
            {
                "a": ["E42_Identifier"],
                "label": "7021987",
                "uri": "http://vocab.getty.edu/tgn/7021987-place"
            },
            {
                "a": ["E48_Place_Name"],
                "label": "Baltimore Independent City"
            }
        ],
        "P2_has_type": {
            "a": ["E55_Type"],
            "label": "Place Depicted",
            "uri": "http://localhost:8080/source/thesauri/geo_type/place_depicted"
        },
        "P48_has_preferred_identifier": {
            "a": ["E42_Identifier"],
            "label": "647244"
        },
        "uri": "http://localhost:8080/source/geography/647244"
    },
    "P48_has_preferred_identifier": {
        "a": ["E42_Identifier"],
        "label": "523"
    },
    "uri": "http://localhost:8080/source/object/523",
    "@context": "http://localhost:8080/publish/JSON/WSP1WS8255-WAM_XMLExport_AAC_Geography_xml-context.json"
}
![div svgdiv_ws8255](https://cloud.githubusercontent.com/assets/1003517/20191496/89d85f88-a73a-11e6-8fdb-88fda6321727.png)

**Comment by workergnome** [comment]
Hey, Ravi—Not sure what I'm looking at there, but I don't see any `skos:exactMatch` terms in it.

**Comment by kateblanch** [comment]
Hi @raviraju, wasn't sure if you meant to close this or not, but David had a follow up (above). In terms of your interpretation, it looks good so far. I will only point out that the different E55_Types might need to be conditionally modeled:
"Place Depicted" would match the P62_depicts property, but other GeoType field values might imply different relationships. Here is a list of the values you'll find in GeoType:

Source of Materials
Place of Origin -- this is the place of the production event
Place of Binding -- see the other issue -- #4 
Place Depicted -- this looks right based on your current modeling

P.S. - I haven't looked over your models yet, maybe you addressed this all, already!

**Comment by kateblanch** [comment]
Hi @raviraju, not sure where we left off with this. I saw there were multiple models and now it seems they've been combined into one model for geography. This single model that works for different geography types is probably the best approach, but others with more expertise could weigh in on that. 
Let me know if you are still stuck on this or should we close? Thanks, Kate

**Comment by raviraju** [comment]
Kate @kateblanch ,
I haven't completed modelling for WAM_AAC_Geography yet, just one for Place Depicted is done, wherein I have taken into skos:exactMatch suggested by David @workergnome.
I have deleted old models inorder to redesign them in accordance with reference material at http://review.americanartcollaborative.org/

David @workergnome , Kate @kateblanch 
I am following a convention of recording the status of each model at readme https://github.com/american-art/wam. So if REVIEW_BY_ISI is set to DONE, you can review and raise any issues to be addressed and accordingly set status of REVIEW_BY_AAC as IN_PROGRESS or DONE. This helps to keep track of status for each of models in WAM.

I shall close this issue, as I am incorporating David's suggestion of skos:exactMatch in models
