### ISSUE TITLE
New Object File / Please Refresh Data

### ISSUE THREAD

**Issue by kateblanch** [american-art/wam#30]
Hi @caknoblock and @bsnikhila  -- 
20 objects from the data set needed to be removed due to rights issues. 
Can you please refresh the WAM data with new file in the Objects folder (https://github.com/american-art/wam/tree/master/WAM_AAC_Objects)? The new file is appended with v3_9-26-2017.

Thanks! Thanks @willhays !

**Comment by willhays** [comment]
Hi all - let me know if there are any updates on this. I'd like to be able to confirm with WAM's rights and repo person that we won't have any potential issue with our AAC data. @caknoblock and @bsnikhila, let me know if y'all need anything else from me.

Thanks!

-W

**Comment by bsnikhila** [comment]
The data has been refreshed.

**Comment by willhays** [comment]
Thanks!
