### ISSUE TITLE
Modelling for Place of Binding in AAC_Geography

### ISSUE THREAD

**Issue by raviraju** [american-art/wam#4]
There are three types of places in data set(Place of Origin, Place Depicted, Place of Binding)
**Place of Origin is modeled as :** 
"E22_Man-Made_Object" "P53_has_former_or_current_location" "E53_Place"
**Place Depicted is modeled as :**
"E22_Man-Made_Object" "P62_depicts" "E53_Place"

Do we have to model Place of Binding, if so, please guide which CIDOC-CRM property is more appropriate

**Comment by workergnome** [comment]
If we are modeling place of Origin, it's probably better to explicitly model the Production event.

```
  E22_Man-Made_Object P108i_was_produced_by E12_Production.
    E12_Production p7_took_place_at E53_Place.
```

**Comment by kateblanch** [comment]
Binding is part of the production event, as the binding is part of the manuscript. Though, binding can happen at the same time as the main production event OR later in time (and it can happen more than once during the life of a manuscript, i.e. a manuscript gets "rebound"). 

Can a production event have types? Can an object have parts that each have their own production event? 
Tagging @edgartdata here for some enlightenment! :)

**Comment by edgartdata** [comment]
Yes, absolutely. Production events can have types (printing, publishing, binding,...). I have never come across an object that has several parts with each their own separate production events, but why not. It might be a tad too complicated for our use here though. How about applying the binding production event to the whole manuscript? Would that be horribly wrong?

**Comment by kateblanch** [comment]
I agree it seems too complex to have an object have several parts each with their own production events. The binding production event can be applied to the whole manuscript, absolutely (as long as it has a "creation" type of production associated with it too).

**Comment by workergnome** [comment]
If I were modeling this, I'd model it as:

```
E22_Man-Made_Object P108i_was_produced_by E12_Production;
     P10i_contains _:binding_event.

_:binding event a E11_Modification;
    P32_used_general_technique aat: 300234771 #bookbinding techniques
    P7_took_place_at  E53_Place.
```
