### ISSUE TITLE
Clarification on (not entered) values for TitleType in AAC_Titles

### ISSUE THREAD

**Issue by raviraju** [american-art/wam#5]
Hi,

We observe a few(3 records) data whose TitleType is (not entered). 
Do we have to model those, setting (not entered) to "Title", as that's the only Title value for all 3 records
  <ObjRecord>
    <ObjectID>88538</ObjectID>
    <DataDateStamp>2016-04-26T13:36:28.670</DataDateStamp>
    <Titles>
      <Title>
        <TitleID>70079</TitleID>
        <TitleDisplayOrder>1</TitleDisplayOrder>
        <Title>Lion Drinking</Title>
        <TitleType>(not entered)</TitleType>
      </Title>
    </Titles>
  </ObjRecord>

**Comment by raviraju** [comment]
Some of the records dont have TitleType. Do we have to model these as well ? Do we need to infer them as Alternate_Title(https://aac-mappings.herokuapp.com/entity/E22_Man-Made_Object#field_1-search_2) ?

  <ObjRecord>
    <ObjectID>20557</ObjectID>
    <DataDateStamp>2016-04-26T13:36:28.670</DataDateStamp>
    <Titles>
      <Title>
        <TitleID>19554</TitleID>
        <TitleDisplayOrder>2</TitleDisplayOrder>
        <Title>Infant Flora</Title>
      </Title>
      <Title>
        <TitleID>55281</TitleID>
        <TitleDisplayOrder>3</TitleDisplayOrder>
        <Title>Bust of a Girl</Title>
      </Title>
      <Title>
        <TitleID>75956</TitleID>
        <TitleDisplayOrder>1</TitleDisplayOrder>
        <Title>Bust of Flora</Title>
        <TitleType>Artist Title</TitleType>
      </Title>
    </Titles>
  </ObjRecord>

**Comment by workergnome** [comment]
For titles that don't have a type, model them as titles, but don't add a type.  (ignore the P2 and everything below it.  That is there to handle things where you know what the type is, but don't have an AAT term for it.

**Comment by workergnome** [comment]
If you know that it's a, say, "Artist Title", you'd want to create an institution thesaurus term, and then you'd want to assign that as the skos:prefLabel for the  E55.  If the type is "Not Entered", you should do the same.

**Comment by kateblanch** [comment]
I think the easiest resolution is for me to fix this in the data. The "(Not entered)" value could default to Title Type = "Title"...this is a data entry error in our source cataloguing system. Given all the other efforts we are all working on, let me just clean up the data :)
@raviraju - if I upload a new Titles data file today, would that set you back? The modeling should not have to change.

**Comment by raviraju** [comment]
@kateblanch - Sure Kate, please upload new Titles data file, and I shall verify if the model created thus far is valid and fix accordingly 
@workergnome - Just to confirm, we have types such as "Alternate"/"Artist Title"/"Transcription"/"Previous Title"/"Text Title" in WAM_Titles apart from "Title". So these various types need to be modelled using http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_1-search_0 "Alternate Titles" model right
Can u cite an example for expected format of institution thesaurus term for title_type

**Comment by kateblanch** [comment]
I just uploaded a new titles data file with "Not Entered" fixed.
Thanks @raviraju, happy holidays!
