### ISSUE TITLE
How to differentiate Constituents into Person/Institution in WAM_AAC_Constituents

### ISSUE THREAD

**Issue by raviraju** [american-art/wam#6]
Using presence of "Gender" tag, helps in classifying constituents as Person for the following:
```
<Role>Painter</Role>
<Role>Artist</Role>
<Role>Goldsmith</Role>
<Role>Sculptor</Role>
<Role>Designer</Role>
```
However it doesn't hold for :
```
<Role>Engraver (Printmaker)</Role>
<Role>Engraver (Inciser)</Role>
```

**Comment by kateblanch** [comment]
Good catch, Ravi! This is something that should be clarified in the data. If I could find an indicator or "Person" vs. "Institution" and reupload the data to include that as a data column, would that help?

**Comment by raviraju** [comment]
@kateblanch Yes that would be helpful

**Comment by kateblanch** [comment]
A new file has been uploaded (name = WAM_XMLExport_AAC_Constituents_V3).
An attribute for ConstituentType is now present. The value will either be Individual, Culture or Institution. 
You can map Individual and Culture BOTH as Individual, and Institution as Institution.

Notes on that:
@edgartdata and @workergnome might disagree but there is gray area around our use of "Culture" as a Type. We don't mean the entire "Japanese Culture" created an object, we mean one, anonymous person who was Japanese created the object. We are working on converting Culture type entries to Individual types in our source data. Please chime in if I'm totally off base / wrong / should be shut down :)

**Comment by workergnome** [comment]
If that's the case, how hard would it be, @raviraju, to model each "culture" person as a distinct ID, per-object?  

If that's a pain, I think we take the data as provided by @kateblanch and go with it.  The data is the data, and nothing is perfect.  (Perhaps add a `p2_has_type` to distinguish them?)

**Comment by raviraju** [comment]
@kateblanch  Since culture type represents an anonymous person, would it be that all info like birth/death/work location, biography would be unknown, and  just role of anonymous person is to be modelled
@workergnome I can either model culture as distinct type similar to institution or treat it as a person with p2_has_type set to culture/individual string

**Comment by workergnome** [comment]
I like the anonymous person, mapped to a culture.  DO we think it's safe to use the "Nationality" model for them, or is "Culture" and "Nationality" too fuzzy a connection?

**Comment by kateblanch** [comment]
Thanks for all the helpful ideas @raviraju  and @workergnome  -- for American art, the Nationality model works great but when we get into other parts of the world, Culture can be different than Nationality. Aztec, Bavarian, Mediterranean are all Cultures whose Nationality would be very different. 

Is it better to choose a mapping for this project / American art or for the whole collection?

@raviraju, safe to model the role of anonymous person (birth/death/work location and biography would be unknown or not relevant for cultures).

Also, whatever is manageable to accomplish within the time constraints! :)

**Comment by workergnome** [comment]
Then for the case of this project, let's `p2_has_type` to an anonymous person, and consider that good enough.  My only request is that the p2 is not per-person, but per group.  So

```
_:anon_japanese_person_one crm:p2_has_type wam:thesaurus/cutures/japanese.
_:anon_japanese_person_two crm:p2_has_type wam:thesaurus/cutures/japanese.

wam:thesaurus/cutures/japanese rdfs:label "Japanese"

```

not

```
_:anon_japanese_person_one crm:p2_has_type wam:anon_japanese_person_one/culture.
_:anon_japanese_person_two crm:p2_has_type wam:anon_japanese_person_two/culture.

wam:anon_japanese_person_one/culture rdfs:label "Japanese".
wam:anon_japanese_person_two/culture rdfs:label "Japanese".

```

I'm making up the paths here—use something consistent to what you've been doing.

**Comment by raviraju** [comment]
@workergnome  David, Thanks for guidelines, have taken comments into consideration and modelled to best of my understanding, please review and let me know if needs to be changed
