### ISSUE TITLE
Model Role of constituent in WAM_AAC_Constituents

### ISSUE THREAD

**Issue by raviraju** [american-art/wam#7]
```
<Role>Painter</Role>
<Role>Artist</Role>
<Role>Manufacturer</Role>
<Role>Jeweler</Role>
```
Do we need to model the role played by the constituent, if so, guide us by pointing how to model them using cidoc-crm, as it isn't part of http://review.americanartcollaborative.org/entity/E39_Actor#field_0-search_0

**Comment by workergnome** [comment]
The issue here is that **role** is work-dependent.  A person could be a painter in the case of one work, but a sculptor in another, and a publisher or architect in another.  

Is this a denormalized column, or are these "global" roles, disconnected from any work?

**Comment by kateblanch** [comment]
The role is within the constituents node, as a text-term (there is no primary key for each role term). These roles are connected to each constituent as they exist related to a given object, this is not a global look-up list of role terms. I have no helpful solutions for mapping...tagging @edgartdata to see how they manage artist role types at YCBA (is it a p2 has type?)

```
Object ID --> Constituent ID --> Role Term ("Artist")
<ObjRecord>
    <ObjectID>169</ObjectID>
    <DataDateStamp>2016-04-26T14:26:05.993</DataDateStamp>
    <Constituents>
      <ObjectRelatedConstituent>
        <ConstituentID>3802</ConstituentID>
        <CreatorDispOrder>1</CreatorDispOrder>
        <Role>Artist</Role>
        <DisplayName>Edward Greene Malbone</DisplayName>
        <Gender>male</Gender>
      </ObjectRelatedConstituent>
    </Constituents>
```

**Comment by kateblanch** [comment]
In the Getty AAT, these roles could be classified under the <people by occupation> node - http://www.getty.edu/vow/AATHierarchy?find=painter&logic=AND&note=&subjectid=300024980

Not sure that is helpful, but wanted to point to the broadest AAT mapping that could be made to reflect the role term types.

**Comment by edgartdata** [comment]
We don't currently map objects related roles at the YCBA unfortunately but I wonder if we could do this?: 
P14 carried out by --> E39 Actor --> P14.1 in the role of --> E55 Type

**Comment by workergnome** [comment]
I think that's what I thought, too, though to do the p14.1 we'd have to use crmpc.

```
    _ :object crm:P108i_was_produced_by _:production_of_david.

    _:sculpting a crmpc:PC14_carried_out_by;
        crmpc:P01_has_domain _:production_of_david;
        crmpc:P02_has_range _:michelangelo; 
        crmpc:P14.1_in_the_role_of aat:1293823.  #sculptor
```

Which is unfortunate indirection, but the only good way to incorporate roles.

For @edgartdata's situation, where people have implicit roles, but not per-object roles, I'd suggest just a `crm:P2_has_type`?

**Comment by kateblanch** [comment]
Whatever works, I'm ok with unfortunate redirections since we're behind the :8ball:

**Comment by edgartdata** [comment]
Yes to p2_has_type for objects related roles.

**Comment by raviraju** [comment]
Discussed with @szeke , and decided not to model Role of Artist, for now
