### ISSUE TITLE
Need to model Work Location in WAM_AAC_Constituents

### ISSUE THREAD

**Issue by raviraju** [american-art/wam#8]
We have:
```
<ThesGeoType>Birth Location</ThesGeoType>
<ThesGeoType>Death Location</ThesGeoType>
```
which can be modeled using http://review.americanartcollaborative.org/entity/E39_Actor#field_14-search_0 and http://review.americanartcollaborative.org/entity/E39_Actor#field_15-search_0 

Guide us in modelling : 
```
<ThesGeoType>Work Location</ThesGeoType>
```

**Comment by workergnome** [comment]
Do you know what that field represents?  I'm not sure of the semantics of that field.  @kateblanch, can you add some clarity?

**Comment by kateblanch** [comment]
Work Location represents the place where the actor spent most of his active career. For example, I was born in New York but my work location is Baltimore (because I work in Baltimore, subsequently I also live in Baltimore but that's a different topic). So Work Location is a geographical attribute of the constituent/actor as he existed on the planet (not necessarily related to any artwork).

**Comment by raviraju** [comment]
@workergnome David, any clue on how to model it ? or shall I ignore it ?

**Comment by edgartdata** [comment]
How about using <ThesGeoType> for Place of Activity?

**Comment by kateblanch** [comment]
Place of Activity sounds like a good conceptual match!

**Comment by workergnome** [comment]
@edgartdata—I think you left off a word there...

**Comment by workergnome** [comment]
perhaps `P74 has current or former residence` ?

It's not as precise a definition, so we're definitely losing information there, but the other way that I could think to do it is as a Move:

```
_:person P25_moved_by _:move.

_:move a E9_Move;
    P26_moved_to _:place;
    P21_had_general_purpose <http://vocab.getty.edu/aat/300387357>
```

**Comment by kateblanch** [comment]
Also OK to ignore this data point if it's becoming too time intensive.

**Comment by edgartdata** [comment]
Sorry about my typo.  I was trying to do something with P12_was_present_at but I think David's model works great.

**Comment by workergnome** [comment]
OK.  Let's go with the Move model, then.
